name: Lint

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint:
    name: Lint code
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
      - uses: actions/checkout@v2
      
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "16.x"
          cache: 'yarn'
          
      - name: Install dependencies
        uses: Borales/actions-yarn@v2.3.0
        
      - name: Run ESLint
        run: yarn eslint
